
name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Install GoLang Migrate
      run: |
        curl -L https://github.com/golang-migrate/migrate/releases/download/v4.18.1/migrate.linux-amd64.tar.gz | tar xvz
        sudo mv migrate /usr/bin/
        which migrate

    - name: Write secrets to app.env file
      run: |
        echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> app.env
        echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> app.env
        echo "DB_SOURCE=${{ secrets.DB_SOURCE }}" >> app.env
        echo "POSTGRES_DB=${{ secrets.POSTGRES_DB }}" >> app.env
        echo "SERVER_ADDRESS=${{ secrets.SERVER_ADDRESS }}" >> app.env
        echo "REDIS_SOURCE=${{ secrets.REDIS_SOURCE }}" >> app.env

    - name: Run migrations
      run: make migrateup

    - name: Test
      run: make test
